# Generated by Django 4.2.5 on 2023-09-19 09:24

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_alter_vehicleimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicleimage",
            options={"get_latest_by": "modified"},
        ),
        migrations.AddField(
            model_name="vehicleimage",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicleimage",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
