# Generated by Django 4.2.5 on 2023-09-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registration",
            "0003_alter_vehicleimage_options_vehicleimage_created_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleimage",
            name="accuracy",
            field=models.FloatField(default=0),
        ),
    ]
